### ISSUE TITLE
Using Library inclusion inside of another CPP file

### ISSUE THREAD

**Issue by LMcCallister** [adafruit/Adafruit_ILI9340#13]
I've used this library a few times before in other projects for arduino, but I'm having trouble this time. I transitioning from using the Arduino IDE to using Visual Studio with the VisualMicro plugin. Part of this is that I am now writing the code inside of .cpp files as opposed to .ino files. 

I've run into a problem with trying to use this library in one of my .cpp files. I include it in the header, and include it in the main .ino file for the program as well. However, when I try to compile it, I get this error: 

TFT_Funcs.cpp.o:(.bss.tft+0x0): multiple definition of `tft
RoboArm.ino:(.bss.tft+0x0): first defined here
collect2.exe*:error: ld returned 1 exit status

However, I can take all of the code from my .h, .cpp, and the .ino, and combine them into a single .ino file in the Arduino IDE, and it works fine.

I've also posted about this on the VisualMicro forum, and the developer thinks that it may be an issue with the library itself. Post is here: http://www.visualmicro.com/forums/YaBB.pl?num=1446330239

**Comment by ladyada** [comment]
this library works great with arduino IDE & has header guards on the .h file so, its very unlikley an issue with our library. you may have to read up on C++ and object instantiation/static object creation since you cannot share names.
