### ISSUE TITLE
RST is optional

### ISSUE THREAD

**Issue by sethten** [adafruit/Adafruit_ILI9340#17]
From what I can tell the RST parameter does not have a default argument. If we opt to not use it, what value should we pass when constructing?

**Comment by ladyada** [comment]
any other pin, and connect it to the arduino RESET

**Comment by sethten** [comment]
Here is an excerpt from the [graphicstest](https://github.com/adafruit/Adafruit_ILI9340/blob/master/examples/graphicstest/graphicstest.ino) example:
```
// These are the pins used for the UNO
// for Due/Mega/Leonardo use the hardware SPI pins (which are different)
#define _sclk 13
#define _miso 12
#define _mosi 11
#define _cs 10
#define _dc 9
#define _rst 8

// Using software SPI is really not suggested, its incredibly slow
//Adafruit_ILI9340 tft = Adafruit_ILI9340(_cs, _dc, _mosi, _sclk, _rst, _miso);
// Use hardware SPI
Adafruit_ILI9340 tft = Adafruit_ILI9340(_cs, _dc, _rst);
```
Here _rst is defined as 8. I do not have a pin number for reset, only the first two (`_cs`,`_dc`). What should I pass as the third argument to the Adafruit_ILI9340 contructor?

**Comment by ladyada** [comment]
some disconnected pin. that's the only thing supported right now.

**Comment by sethten** [comment]
Here is an excerpt from the [graphicstest](https://github.com/adafruit/Adafruit_ILI9340/blob/master/examples/graphicstest/graphicstest.ino) example:
```
// These are the pins used for the UNO
// for Due/Mega/Leonardo use the hardware SPI pins (which are different)
#define _sclk 13
#define _miso 12
#define _mosi 11
#define _cs 10
#define _dc 9
#define _rst 8

// Using software SPI is really not suggested, its incredibly slow
//Adafruit_ILI9340 tft = Adafruit_ILI9340(_cs, _dc, _mosi, _sclk, _rst, _miso);
// Use hardware SPI
Adafruit_ILI9340 tft = Adafruit_ILI9340(_cs, _dc, _rst);
```
Here _rst is defined as 8. I do not have a pin number for reset, only the [first two](https://github.com/sethten/EVs_UIModule/blob/master/EVs_UIModule.h#L62) (`_cs`,`_dc`). What should I pass as the third argument to the Adafruit_ILI9340 constructor?

**Comment by sethten** [comment]
@ladyada Okay, thank you!
