### ISSUE TITLE
Multiple (2) displays on one (Teensy3.2) micro

### ISSUE THREAD

**Issue by pljakobs** [adafruit/Adafruit_ILI9340#20]
**Short description:**
driving two ILI9340 displays in parallel doesn't work, only one display shows content

**Details**
I'm not sure if this is a display driver issue or an SPI issue (although: switching from HW to SW SPI doesn't help, making SPI itself less probable) but:

I'm trying to run two (or potentially more) ILI9340 displays from one single micro. For that, I wire them up parallel on the SPI bus (MOSI, MISO, SCLK) but give them dedicated RST, D/C and CS signals.

I believe(!) that I'm obeying the rules for hardware SPI pins on the teensy:

[code]
#define _sclk 13
#define _miso 12
#define _mosi 11
#define _cs   10
#define _dc   9
#define _rst  8
#define _led  6
#define _cs1  15
#define _rst1 21
#define _dc1  20
[/code]

I'm sure my wiring is correct because when I don't instantiate one of the displays, the other one will work fine.
Looking at the logic analyzer, I can see that both displays are being driven, which lets me think that maybe the initialization for the 2nd instance fails? (although, interestingly, no matter in which order they are instantiated, the one with the lower dc/rst/cs pin numbers wins - if the behaviour wasn't identical in software SPI, I would assume it's a limitation of the hardware SPI implementation)

*A few looks at the signals:*
![dual-display-startup](https://user-images.githubusercontent.com/13985375/27798496-bb36d542-6011-11e7-9bc1-f0208c85d7ec.png)
![dual-display-init](https://user-images.githubusercontent.com/13985375/27798570-0c78613c-6012-11e7-9625-5d7df611d549.png)
![dual-display-multiple-cycles](https://user-images.githubusercontent.com/13985375/27798577-12a7c674-6012-11e7-8913-4c293c2abb4d.png)
![dual-display-display-1-cycle](https://user-images.githubusercontent.com/13985375/27798580-156d2e30-6012-11e7-9802-77deac697241.png)
![dual-display-display-2-cycle](https://user-images.githubusercontent.com/13985375/27798583-17551f6e-6012-11e7-82c9-7dac63990a58.png)

**Comment by ladyada** [comment]
hmm - not sure! could be object state or something weird with the driver or maybe a bug :) 
one thing you can try just to start is use totally separate 'bitbang' pins. does it work then?

**Comment by PaintYourDragon** [comment]
Just speculating right now, I'm heading out for the holiday and don't have a moment to experiment right now, but...

Library pre-dates SPI transactions in the Arduino ecosystem. It's possible something is going on with the SPI library doing its own thing with the CS pin(s).

**Comment by pljakobs** [comment]
the interesting part is: according to the signal analyzer, CS looks, at least at first glance, to be all right. 
I'll have a look at the code.
My hunch is: I think the second Display doesn't get fully initialized.

**Comment by ladyada** [comment]
oh jeez yah this is ILI9340 - please try the ILI9341 library, its 99% code compatible

**Comment by pljakobs** [comment]
wow, the ILI9341 is about twice as fast as the ILI9340 library... seems there was some major improvement...
My second display won't work, still. 
But: now it doesn't seem to work at all, even in a one display setup. And I would swear that it was ok earlier on. Oh my...

**Comment by ladyada** [comment]
this library is deprecated, you can use Adafruit_ILI9341 instead!
