### ISSUE TITLE
SD.h not working on teensy 3.1

### ISSUE THREAD

**Issue by dereknheiley** [adafruit/Adafruit_ILI9340#7]
i have a pjrc shield for micro sd that works fine with SD.h and SdFat.h, but i can't seem to get the SD card reader working with the Adafruit_ILI9340 lcd & micro shield for the spitftbitmap example

LCD works with teensy 3.1 using:
D/C pin 9
RST pin 8
CS pin 10
MOSI pin 11
MISO pin 12
SCK pin 13

tried hooking up the SDSC to:
pin 4 
pin 15 (changing the code, since this is also teensy 3.1 SPI cs pin)
pin 10 (changing the code, since standard ss / cs pin for the PJRC shield with SD.h)

All fail the SD.begin(SD_CS). I even tried moving the lcd CS to 15, and letting SDCS be on 10 and the LCD works once i change the code, but the SD still won't begin / init

I was successful using the lcd & micro sheild with a different SdFat.h library, so i'm wondering where the issue is with using the SD library, on this shield, with a teensy 3.1

**Comment by ladyada** [comment]
this library is deprecated, you can use Adafruit_ILI9341 instead!
